=== hmrc/property-business-api/resources/public/api/conf/4.0/schemas/uk_property_period_summary_retrieve/response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve UK Property Income & Expenses Period Summary",
  "description": "This endpoint allows a developer to retrieve the income and expenses for a UK property business, that occurred between two dates. A National Insurance number, business ID, tax year and submission ID are required.",
  "type": "object",
  "properties": {
    "submittedOn": {
      "type": "string",
      "description": "The date the UK property were submitted, in the format `YYYY-MM-DDThh:mm:ss.SSSZ`",
      "example": "2020-07-07T10:59:47.544Z"
    },
    "fromDate": {
      "type": "string",
      "description": "The first day that the income and expenses period summary covers. Must conform to the format YYYY-MM-DD",
      "example": "2020-01-01"
    },
    "toDate": {
      "type": "string",
      "description": "The last day that the income and expenses period summary covers. Must conform to the format YYYY-MM-DD",
      "example": "2020-01-31"
    },
    "ukFhlProperty": {
      "type": "object",
      "description": "Object holding the income and expenses of the user's Furnished Holiday Letting (FHL) in the United Kingdom for the period. (At least one of income or expenses should be present).",
      "properties": {
        "income": {
          "type": "object",
          "description": "Object holding the income details for the period.",
          "properties": {
            "periodAmount": {
              "description": "Total rents from property, ground rents and rent charges but not rent-a-room. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "taxDeducted": {
              "description": "The tax deducted from income. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "rentARoom": {
              "type": "object",
              "description": "Object holding the rents received for the period.",
              "properties": {
                "rentsReceived": {
                  "description": "Total rents received from properties. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                  "type": "number",
                  "multipleOf": 0.01,
                  "minimum": 0.00,
                  "maximum": 99999999999.99,
                  "example": "5000.99"
                }
              },
              "additionalProperties": false
            }
          },
          "additionalProperties": false
        },
        "expenses": {
          "type": "object",
          "description": "Object holding the expenses for the period.",
          "properties": {
            "premisesRunningCosts": {
              "description": "Rent, rates, insurance, ground rents and other costs. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "repairsAndMaintenance": {
              "description": "Property repairs and maintenance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "financialCosts": {
              "description": "Loan interest and other financial costs. The value must be between 0 and 99999999999.99 up to 2 decimal places",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "professionalFees": {
              "description": "Legal, management and other professional fees. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "costOfServices": {
              "description": "Cost of services provided, including wages. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "other": {
              "description": "Other allowable property expenses. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "travelCosts": {
              "description": "Car, van and travel costs incurred in running a property business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "rentARoom": {
              "type": "object",
              "description": "Object holding the rents claimed for the period.",
              "properties": {
                "amountClaimed": {
                  "description": "The amount of UK Furnished Holiday Lettings rent claimed. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                  "type": "number",
                  "multipleOf": 0.01,
                  "minimum": 0.00,
                  "maximum": 99999999999.99,
                  "example": "5000.99"
                }
              },
              "additionalProperties": false
            },
            "consolidatedExpenses": {
              "description": "The sum of all expenses for the specified period. If consolidatedExpenses is returned, values for individual expenses (premisesRunningCosts, repairsAndMaintenance, financialCosts, professionalFees, costOfServices, other, travelCosts, rentARoom) are not returned. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "ukNonFhlProperty": {
      "type": "object",
      "description": "Object  holding the income and expenses of the UK property business - excluding Furnished Holiday Lettings (FHL) for the period. (At least one of income or expenses should be present).",
      "properties": {
        "income": {
          "type": "object",
          "description": "Object holding the income details for the period.",
          "properties": {
            "premiumsOfLeaseGrant": {
              "description": "Premiums received for the grant of a lease and other lump sums to possess a property. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "reversePremiums": {
              "description": "Amount paid by a landlord or outgoing tenant to induce a new tenant to enter into a leasehold agreement. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "periodAmount": {
              "description": "Total rents from property (but not ground rents, rent charges and rent-a-room rental income). The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "taxDeducted": {
              "description": "Tax already deducted from the rental income. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "otherIncome": {
              "description": "Total amount of rent and any income for services provided to tenants. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "rentARoom": {
              "type": "object",
              "description": "Object holding the rents received for the period.",
              "properties": {
                "rentsReceived": {
                  "description": "Total rents received from properties. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                  "type": "number",
                  "multipleOf": 0.01,
                  "minimum": 0.00,
                  "maximum": 99999999999.99,
                  "example": "5000.99"
                }
              },
              "additionalProperties": false
            }
          },
          "additionalProperties": false
        },
        "expenses": {
          "type": "object",
          "description": "Object holding the expenses for the period.",
          "properties": {
            "premisesRunningCosts": {
              "description": "Rent, rates, insurance, ground rents and other costs. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "repairsAndMaintenance": {
              "description": "Property repairs and maintenance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "financialCosts": {
              "description": "Loan interest and other financial costs. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "professionalFees": {
              "description": "Legal, management and other professional fees. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "costOfServices": {
              "description": "Cost of services provided, including wages. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "other": {
              "description": "Other allowable property expenses. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "residentialFinancialCost": {
              "description": "The residential financial cost deductible from rental income (tax relief). The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "travelCosts": {
              "description": "Car, van and travel costs incurred in running a property business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "residentialFinancialCostsCarriedForward": {
              "description": "Amount of residential financial costs carried forward. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            },
            "rentARoom": {
              "type": "object",
              "description": "Object holding the rents claimed for the period.",
              "properties": {
                "amountClaimed": {
                  "description": "The amount of UK Furnished Holiday Lettings rent claimed. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                  "type": "number",
                  "multipleOf": 0.01,
                  "minimum": 0.00,
                  "maximum": 99999999999.99,
                  "example": "5000.99"
                }
              },
              "additionalProperties": false
            },
            "consolidatedExpenses": {
              "description": "The sum of all expenses for the specified period. You can either submit a consolidatedExpenses value or individual expenses (premisesRunningCosts, repairsAndMaintenance, financialCosts, professionalFees, costOfServices, other, residentialFinancialCost, travelCosts, residentialFinancialCostsCarriedForward, rentARoom) The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0.00,
              "maximum": 99999999999.99,
              "example": "5000.99"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "A list of endpoint links that indicate possible actions related to the current resource.",
        "properties": {
          "href": {
            "description": "The relative url of the endpoint",
            "type": "string",
            "example": "/individuals/business/property/uk/AA999999A/XAIS12345678910/period/2022-23/4557ecb5-fd32-48cc-81f5-e6acd1099f3c"
          },
          "rel": {
            "description": "A label for the endpoint, which describes how it is related to the current resource. The rel will be self where the action is retrieval of the same resource",
            "type": "string",
            "enum": [
              "self",
              "list-property-period-summaries",
              "amend-uk-property-period-summary"
            ]
          },
          "method": {
            "description": "The HTTP method type for the endpoint",
            "type": "string",
            "enum": [
              "GET",
              "PUT"
            ]
          }
        },
        "required": [
          "href",
          "rel",
          "method"
        ],
        "additionalProperties": false
      },
      "additionalItems": false
    }
  },
  "required": [
    "submittedOn",
    "fromDate",
    "toDate"
  ],
  "additionalProperties": false
}

=== hmrc/property-business-api/resources/public/api/conf/2.0/examples/uk_property_period_summary_retrieve/response.json
{
  "submittedOn": "2021-10-21T08:57:47Z",
  "fromDate": "2020-01-01",
  "toDate": "2020-01-31",
  "ukFhlProperty": {
    "income": {
      "periodAmount": 5000.99,
      "taxDeducted": 3123.21,
      "rentARoom": {
        "rentsReceived": 532.12
      }
    },
    "expenses": {
      "premisesRunningCosts": 4141.21,
      "repairsAndMaintenance": 582.21,
      "financialCosts": 829.39,
      "professionalFees": 4992.31,
      "costOfServices": 98.21,
      "other": 29.48,
      "travelCosts": 48.93,
      "rentARoom": {
        "amountClaimed": 88.21
      }
    }
  },
  "ukNonFhlProperty": {
    "income": {
      "premiumsOfLeaseGrant": 42.12,
      "reversePremiums": 84.31,
      "periodAmount": 9884.93,
      "taxDeducted": 842.99,
      "otherIncome": 31.44,
      "rentARoom": {
        "rentsReceived": 947.66
      }
    },
    "expenses": {
      "premisesRunningCosts": 4141.21,
      "repairsAndMaintenance": 582.21,
      "financialCosts": 829.39,
      "professionalFees": 4992.31,
      "costOfServices": 98.21,
      "other": 29.48,
      "residentialFinancialCost": 2884.99,
      "travelCosts": 48.93,
      "residentialFinancialCostsCarriedForward": 483.91,
      "rentARoom": {
        "amountClaimed": 88.21
      }
    }
  },
  "links": [
    {
      "href":"/individuals/business/property/uk/AA999999A/XAIS12345678910/period/2022-23/4557ecb5-fd32-48cc-81f5-e6acd1099f3c",
      "method": "PUT",
      "rel": "amend-uk-property-period-summary"
    },
    {
      "href":"/individuals/business/property/uk/AA999999A/XAIS12345678910/period/2022-23/4557ecb5-fd32-48cc-81f5-e6acd1099f3c",
      "method": "GET",
      "rel": "self"
    },
    {
      "href":"/individuals/business/property/uk/AA999999A/XAIS12345678910/period/2022-23",
      "method": "GET",
      "rel": "list-property-period-summaries"
    }
  ]
}

=== hmrc/property-business-api/resources/public/api/conf/3.0/examples/uk_property_period_summary_retrieve/consolidated_response.json
{
  "submittedOn": "2023-10-21T10:59:47.544Z",
  "fromDate": "2022-07-21",
  "toDate": "2022-08-21",
  "ukFhlProperty": {
    "income": {
      "periodAmount": 5000.99,
      "taxDeducted": 3123.21,
      "rentARoom": {
        "rentsReceived": 532.12
      }
    },
    "expenses": {
      "consolidatedExpenses": 988.18
    }
  },
  "ukNonFhlProperty": {
    "income": {
      "premiumsOfLeaseGrant": 4889.23,
      "reversePremiums": 847.35,
      "periodAmount": 747.45,
      "taxDeducted": 984.29,
      "otherIncome": 954.32,
      "rentARoom": {
        "rentsReceived": 488.39
      }
    },
    "expenses": {
      "consolidatedExpenses": 988.18
    }
  },
  "links": [
    {
      "href": "/individuals/business/property/uk/KZ816096B/XAIS12345678910/period/2022-23/4557ecb5-fd32-48cc-81f5-e6acd1099f3c",
      "method": "PUT",
      "rel": "amend-uk-property-period-summary"
    },
    {
      "href": "/individuals/business/property/uk/KZ816096B/XAIS12345678910/period/2022-23/4557ecb5-fd32-48cc-81f5-e6acd1099f3c",
      "method": "GET",
      "rel": "self"
    },
    {
      "href": "/individuals/business/property/KZ816096B/XAIS12345678910/period/2022-23",
      "method": "GET",
      "rel": "list-property-period-summaries"
    }
  ]
}
