=== hmrc/property-business-api/resources/public/api/conf/2.0/schemas/historic_uk_non_fhl_period_summary_retrieve/response.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "object",
  "properties": {
    "fromDate": {
      "type": "string",
      "description": "The first day that the income and expenses period summary covers. Must conform to the format YYYY-MM-DD",
      "example": "2020-01-01"
    },
    "toDate": {
      "type": "string",
      "description": "The last day that the income and expenses period summary covers. Must conform to the format YYYY-MM-DD",
      "example": "2020-01-31"
    },
    "income": {
      "type": "object",
      "description": "Object containing the details about income",
      "properties": {
        "periodAmount": {
          "type": "number",
          "description": "Total rents from property, ground rents and rent charges but not rent-a-room.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "premiumsOfLeaseGrant": {
          "type": "number",
          "description": "Total rents from property, ground rents and rent charges but not rent-a-room.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "reversePremiums": {
          "type": "number",
          "description": "Total rents from property, ground rents and rent charges but not rent-a-room.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "otherIncome": {
          "type": "number",
          "description": "Total rents from property, ground rents and rent charges but not rent-a-room.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "taxDeducted": {
          "type": "number",
          "description": "Tax already deducted from the rental income.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "rentARoom": {
          "type": "object",
          "description": "Objects holding rents received for the period",
          "properties": {
            "rentsReceived": {
              "type": "number",
              "description": "Total rents received from properties.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            }
          }
        }
      }
    },
    "expenses": {
      "type": "object",
      "description": "Object holding expenses for the period",
      "properties": {
        "premisesRunningCosts": {
          "type": "number",
          "description": "Rent, rates, insurance, ground rents and other costs.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "repairsAndMaintenance": {
          "type": "number",
          "description": "Property repairs and maintenance.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "financialCosts": {
          "type": "number",
          "description": "Loan interest and other financial costs.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "professionalFees": {
          "type": "number",
          "description": "Legal, management and other professional fees.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "costOfServices": {
          "type": "number",
          "description": "Cost of services provided, including wages.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "other": {
          "type": "number",
          "description": "Other allowable property expenses.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "consolidatedExpenses": {
          "type": "number",
          "description": "The sum of all expenses for the specified period and it should not appear at the same time as all the other expenses. \nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "travelCosts": {
          "type": "number",
          "description": "Car, van and travel costs incurred in running a property business.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "residentialFinancialCostsCarriedForward": {
          "type": "number",
          "description": "Amount of residential financial costs carried forward.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "residentialFinancialCost": {
          "type": "number",
          "description": "Captures residential financial cost that can be deductible from rental income (tax relief). The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "1000.45"
        },
        "rentARoom": {
          "type": "object",
          "description": "Object holding the amount claimed for the period",
          "properties": {
            "amountClaimed": {
              "type": "number",
              "description": "The amount of UK Furnished Holiday Lettings rent claimed.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            }
          }
        }
      }
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "href": {
            "description": "The relative url of the endpoint",
            "type": "string",
            "example": "/individuals/business/property/uk/period/furnished-holiday-lettings/TC663795B/2017-04-06_2017-07-04"
          },
          "method": {
            "description": "The HTTP method type for the endpoint",
            "type": "string",
            "enum": [
              "PUT",
              "GET"
            ]
          },
          "rel": {
            "description": "A label for the endpoint, which describes how it is related to the current resource. The rel will be self where the action is retrieval of the same resource",
            "type": "string",
            "enum": [
              "amend-uk-property-historic-non-fhl-period-summary",
              "self",
              "list-uk-property-historic-non-fhl-period-summaries"
            ]
          }
        },
        "required": [
          "href",
          "rel",
          "method"
        ]
      }
    }
  },
  "required": [
    "fromDate",
    "toDate"
  ]
}

=== hmrc/property-business-api/resources/public/api/conf/4.0/examples/historic_uk_non_fhl_period_summary_retrieve/response.json
{
  "fromDate": "2020-01-01",
  "toDate": "2020-01-31",
  "income": {
    "periodAmount": 200,
    "premiumsOfLeaseGrant": 200,
    "reversePremiums": 200,
    "otherIncome": 200,
    "taxDeducted": 100,
    "rentARoom": {
      "rentsReceived": 100
    }
  },
  "expenses": {
    "premisesRunningCosts": 200,
    "repairsAndMaintenance": 200,
    "financialCosts": 200,
    "professionalFees": 200,
    "costOfServices": 200,
    "other": 200,
    "travelCosts": 200,
    "residentialFinancialCostsCarriedForward": 200,
    "residentialFinancialCost": 200,
    "rentARoom": {
      "amountClaimed": 200
    }
  },
  "links": [
    {
      "href": "/individuals/business/property/uk/period/non-furnished-holiday-lettings/TC663795B/2020-01-01_2020-01-31",
      "method": "PUT",
      "rel": "amend-uk-property-historic-non-fhl-period-summary"
    },
    {
      "href": "/individuals/business/property/uk/period/non-furnished-holiday-lettings/TC663795B/2020-01-01_2020-01-31",
      "method": "GET",
      "rel": "self"
    },
    {
      "href": "/individuals/business/property/uk/period/non-furnished-holiday-lettings/TC663795B",
      "method": "GET",
      "rel": "list-uk-property-historic-non-fhl-period-summaries"
    }
  ]
}
