=== hmrc/property-business-api/resources/public/api/conf/4.0/schemas/historic_uk_non_fhl_period_summary_retrieve/def1/response.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "object",
  "properties": {
    "fromDate": {
      "type": "string",
      "description": "The first day that the income and expenses period summary covers. Must conform to the format YYYY-MM-DD",
      "example": "2020-01-01"
    },
    "toDate": {
      "type": "string",
      "description": "The last day that the income and expenses period summary covers. Must conform to the format YYYY-MM-DD",
      "example": "2020-01-31"
    },
    "income": {
      "type": "object",
      "description": "Object containing the details about income",
      "properties": {
        "periodAmount": {
          "type": "number",
          "description": "Total rents from property, ground rents and rent charges but not rent-a-room.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "premiumsOfLeaseGrant": {
          "type": "number",
          "description": "Total rents from property, ground rents and rent charges but not rent-a-room.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "reversePremiums": {
          "type": "number",
          "description": "Total rents from property, ground rents and rent charges but not rent-a-room.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "otherIncome": {
          "type": "number",
          "description": "Total rents from property, ground rents and rent charges but not rent-a-room.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "taxDeducted": {
          "type": "number",
          "description": "Tax already deducted from the rental income.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "rentARoom": {
          "type": "object",
          "description": "Objects holding rents received for the period",
          "properties": {
            "rentsReceived": {
              "type": "number",
              "description": "Total rents received from properties.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            }
          }
        }
      }
    },
    "expenses": {
      "type": "object",
      "description": "Object holding expenses for the period",
      "properties": {
        "premisesRunningCosts": {
          "type": "number",
          "description": "Rent, rates, insurance, ground rents and other costs.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "repairsAndMaintenance": {
          "type": "number",
          "description": "Property repairs and maintenance.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "financialCosts": {
          "type": "number",
          "description": "Loan interest and other financial costs.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "professionalFees": {
          "type": "number",
          "description": "Legal, management and other professional fees.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "costOfServices": {
          "type": "number",
          "description": "Cost of services provided, including wages.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "other": {
          "type": "number",
          "description": "Other allowable property expenses.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "consolidatedExpenses": {
          "type": "number",
          "description": "The sum of all expenses for the specified period. If consolidatedExpenses is returned, values for individual expenses (premisesRunningCosts, repairsAndMaintenance, financialCosts, professionalFees, costOfServices, other, travelCosts, residentialFinancialCostsCarriedForward, residentialFinancialCost, rentARoom) are not returned. \nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "travelCosts": {
          "type": "number",
          "description": "Car, van and travel costs incurred in running a property business.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "residentialFinancialCostsCarriedForward": {
          "type": "number",
          "description": "Amount of residential financial costs carried forward.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "5000.99"
        },
        "residentialFinancialCost": {
          "type": "number",
          "description": "Captures residential financial cost that can be deductible from rental income (tax relief). The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "example": "1000.45"
        },
        "rentARoom": {
          "type": "object",
          "description": "Object holding the amount claimed for the period",
          "properties": {
            "amountClaimed": {
              "type": "number",
              "description": "The amount of UK Furnished Holiday Lettings rent claimed.\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            }
          }
        }
      }
    }
  },
  "required": [
    "fromDate",
    "toDate"
  ]
}

=== hmrc/property-business-api/resources/public/api/conf/4.0/examples/historic_uk_non_fhl_period_summary_create/consolidated_request.json
{
  "fromDate": "2019-03-11",
  "toDate": "2020-04-23",
  "income": {
    "periodAmount": 123.45,
    "premiumsOfLeaseGrant": 2355.45,
    "reversePremiums": 454.56,
    "otherIncome": 567.89,
    "taxDeducted": 234.53,
    "rentARoom": {
      "rentsReceived": 567.56
    }
  },
  "expenses":{
    "consolidatedExpenses": 235.78
  }
}

=== hmrc/property-business-api/resources/public/api/conf/4.0/examples/historic_uk_non_fhl_period_summary_retrieve/def1/consolidated_response.json
{
  "fromDate": "2020-01-01",
  "toDate": "2020-01-31",
  "income": {
    "periodAmount": 200,
    "premiumsOfLeaseGrant": 200,
    "reversePremiums": 200,
    "otherIncome": 200,
    "taxDeducted": 100,
    "rentARoom": {
      "rentsReceived": 100
    }
  },
  "expenses": {
    "consolidatedExpenses": 200
  }
}

=== hmrc/property-business-api/resources/public/api/conf/4.0/examples/historic_uk_non_fhl_period_summary_retrieve/def1/response.json
{
  "fromDate": "2020-01-01",
  "toDate": "2020-01-31",
  "income": {
    "periodAmount": 200,
    "premiumsOfLeaseGrant": 200,
    "reversePremiums": 200,
    "otherIncome": 200,
    "taxDeducted": 100,
    "rentARoom": {
      "rentsReceived": 100
    }
  },
  "expenses": {
    "premisesRunningCosts": 200,
    "repairsAndMaintenance": 200,
    "financialCosts": 200,
    "professionalFees": 200,
    "costOfServices": 200,
    "other": 200,
    "travelCosts": 200,
    "residentialFinancialCostsCarriedForward": 200,
    "residentialFinancialCost": 200,
    "rentARoom": {
      "amountClaimed": 200
    }
  }
}
