=== hmrc/property-business-api/resources/public/api/conf/1.0/schemas/create_foreign_property_request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Create Foreign Property Income & Expenditure Period",
  "description": "This endpoint allows the developer to submit the income and expenditure for a foreign property business that occurred between two dates. This submission is for either or both of Furnished Holiday Lettings (FHL) in the European Economic Area (EEA) and all other foreign Property submissions. A National Insurance number and business ID are required.",
  "type": "object",
  "properties": {
    "fromDate": {
      "description": "The first day that the income and expenditure period summary covers. Must conform to the format YYYY-MM-DD.",
      "type": "string",
      "example": "2018-04-06"
    },
    "toDate": {
      "description": "The last day that the income and expenditure period summary covers. Must conform to the format YYYY-MM-DD.",
      "type": "string",
      "example": "2019-04-06"
    },
    "foreignFhlEea": {
      "description": "Object holding the income and expenditure of the user's Furnished Holiday Lettings (FHL) in the European Economic Area (EEA) for the period",
      "type": "object",
      "properties": {
        "income": {
          "description": "Object holding the income details for the period.",
          "type": "object",
          "properties": {
            "rentAmount": {
              "description": "Total rent and other income from property. The value must be between 0 and 99999999999.99.",
              "type": "number",
              "example": "5000.99"
            },
            "taxDeducted": {
              "description": "Tax taken off rental Income (applies to non-resident landlords only). The value must be greater than 0 and up to 99999999999.99.",
              "type": "number",
              "example": "5000.99"
            }
          },
          "required": [
            "rentAmount"
          ]
        },
        "expenditure": {
          "description": "Object holding the expenditure for the period.",
          "type": "object",
          "properties": {
            "consolidatedExpenses": {
              "description": "The sum of all expenses for the specified period. The value must be greater than 0 and up to 99999999999.99.",
              "type": "number",
              "example": "5000.99"
            }
          }
        }
      },
      "required": [
        "income"
      ]
    },
    "foreignProperty": {
      "description": "Array holding the income and expenses of the user's foreign property business - excluding Furnished Holiday Lettings (FHL) in the European Economic Area (EEA) - for the period.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "countryCode": {
            "description": "A three-letter code that represents a country name. This must be an ISO 3166-1 Alpha-3 value.",
            "type": "string",
            "example": "FRA"
          },
          "income": {
            "description": "Object holding the income details for the period.",
            "type": "object",
            "properties": {
              "rentIncome": {
                "description": "An object containing the amount taken in rent and any tax deducted.",
                "type": "object",
                "properties": {
                  "rentAmount": {
                    "description": "The total amount of rental income. The value must be between 0 and 99999999999.99.",
                    "type": "number",
                    "example": "5000.99"
                  },
                  "taxDeducted": {
                    "description": "Tax already taken off from the rental income. The value must be greater than 0 and up to 99999999999.99.",
                    "type": "number",
                    "example": "5000.99"
                  }
                },
                "required": [
                  "rentAmount"
                ]
              },
              "foreignTaxCreditRelief": {
                "description": "A boolean indicating whether Foreign Tax Credit Relief (FTCR) has been claimed. The value must be true or false.",
                "type": "boolean",
                "example": "true"
              },
              "premiumOfLeaseGrant": {
                "description": "Premiums received for the grant of a lease and other lump sums to possess a property. The value must be greater than 0 and up to 99999999999.99.",
                "type": "number",
                "example": "5000.99"
              },
              "otherPropertyIncome": {
                "description": "Other income from property, such as rent charges and ground rents, income from letting others tip waste on your land, and income for the use of a caravan or houseboat at a fixed location. The value must be greater than 0 and up to 99999999999.99.",
                "type": "number",
                "example": "5000.99"
              },
              "foreignTaxTakenOff": {
                "description": "The total amount of foreign tax taken off your income. The value must be greater than 0 and up to 99999999999.99.",
                "type": "number",
                "example": "5000.99"
              },
              "specialWithholdingTaxOrUKTaxPaid": {
                "description": "Tax withheld (in UK Pounds) on certain payments to UK residents or UK Tax taken off rental Income (applies to non-resident landlords only). The value must be greater than 0 and up to 99999999999.99.",
                "type": "number",
                "example": "5000.99"
              }
            },
            "required": [
              "rentIncome",
              "foreignTaxCreditRelief"
            ]
          },
          "expenditure": {
            "description": "Object holding the expenditure for the period.",
            "type": "object",
            "properties": {
              "residentialFinancialCost": {
                "description": "The residential financial cost that can be deductible from rental income (tax relief). The value must be greater than 0 and up to 99999999999.99.",
                "type": "number",
                "example": "5000.99"
              },
              "broughtFwdResidentialFinancialCost": {
                "description": "Amount of relief brought forward for restricted residential financial costs. The value must be greater than 0 and up to 99999999999.99.",
                "type": "number",
                "example": "5000.99"
              },
              "consolidatedExpenses": {
                "description": "The sum of all expenses for the specified period. The value must be greater than 0 and up to 99999999999.99.",
                "type": "number",
                "example": "5000.99"
              }
            }
          }
        },
        "required": [
          "countryCode",
          "income"
        ]
      }
    }
  },
  "required": [
    "fromDate",
    "toDate"
  ]
}

=== hmrc/property-business-api/resources/public/api/conf/2.0/examples/foreign_property_period_summary_create/consolidated_request.json
{
  "fromDate": "2018-04-06",
  "toDate": "2019-04-06",
  "foreignFhlEea": {
    "income": {
      "rentAmount": 5000.99
    },
    "expenditure": {
      "consolidatedExpenses": 5000.99
    }
  },
  "foreignProperty": [
    {
      "countryCode": "FRA",
      "income": {
        "rentIncome": {
          "rentAmount": 5000.99
        },
        "foreignTaxCreditRelief": false,
        "premiumOfLeaseGrant": 5000.99,
        "otherPropertyIncome": 5000.99,
        "foreignTaxTakenOff": 5000.99,
        "specialWithholdingTaxOrUKTaxPaid": 5000.99
      },
      "expenditure": {
        "residentialFinancialCost": 200.25,
        "broughtFwdResidentialFinancialCost": 100.25,
        "consolidatedExpenses": 100.25
      }
    }
  ]
}
