=== hmrc/property-business-api/resources/public/api/conf/2.0/schemas/uk_property_annual_submission_retrieve/response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve a UK property business annual submission",
  "description": "Retrieve a UK property business annual submission",
  "type": "object",
  "properties": {
    "submittedOn": {
      "type": "string",
      "description": "The date the UK property was submitted, in the format YYYY-MM-DDThh:mm:ss.SSSZ",
      "example": "2022-07-07T10:59:47.544Z"
    },
    "ukFhlProperty": {
      "type": "object",
      "description": "Object holding the adjustments and allowances of the user's Furnished Holiday Letting (FHL) in the United Kingdom.",
      "properties": {
        "adjustments": {
          "type": "object",
          "description": "Object holding UK FHL Property Adjustments.",
          "properties": {
            "lossBroughtForward": {
              "type": "number",
              "description": "Loss brought forward from earlier years. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "privateUseAdjustment": {
              "type": "number",
              "description": "Any expenses incurred not solely for the property business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "balancingCharge": {
              "type": "number",
              "description": "A charge for an item, for which capital allowance was claimed, but has since been sold, given away or is no longer in use. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "periodOfGraceAdjustment": {
              "type": "boolean",
              "description": "A boolean to identify  a property which didn't qualify for FHL this year but qualified the previous year. The value must be true or false.",
              "example": "true"
            },
            "businessPremisesRenovationAllowanceBalancingCharges": {
              "type": "number",
              "description": "Income from the sale or grant of a long lease for a premium of renovated business premises within 7 years of first use. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "nonResidentLandlord": {
              "type": "boolean",
              "description": "A boolean to identify  that the user is a Non-Resident Landlord. The value must be true or false.",
              "example": "false"
            },
            "rentARoom": {
              "type": "object",
              "description": "Object holding UK FHL Rent A Room income shared.",
              "properties": {
                "jointlyLet": {
                  "type": "boolean",
                  "description": "A boolean to identify that the Rent A Room income (RAR) is shared with another individual. The value must be true or false.",
                  "example": "true"
                }
              },
              "required": [
                "jointlyLet"
              ]
            }
          },
          "additionalProperties": false,
          "required": [
            "nonResidentLandlord",
            "periodOfGraceAdjustment"
          ]
        },
        "allowances": {
          "type": "object",
          "description": "Object holding UK FHL Property Allowances.",
          "properties": {
            "annualInvestmentAllowance": {
              "type": "number",
              "description": "The amount claimed on equipment bought (except cars) up to maximum annual amount. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "businessPremisesRenovationAllowance": {
              "type": "number",
              "description": "The allowance amount for renovation or conversion of derelict business properties. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "otherCapitalAllowance": {
              "type": "number",
              "description": "All other capital allowances. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "propertyIncomeAllowance": {
              "type": "number",
              "description": "The amount of Tax exemption for individuals with income from land or property. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "electricChargePointAllowance": {
              "type": "number",
              "description": "The expenditure incurred on electric charge-point equipment. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "zeroEmissionsCarAllowance": {
              "type": "number",
              "description": "The amount of zero emissions car allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "ukNonFhlProperty": {
      "type": "object",
      "description": "Object holding allowances and adjustments for UK property business - excluding Furnished Holiday Lettings (FHL) - for the period.",
      "properties": {
        "adjustments": {
          "type": "object",
          "description": "Object holding UK Non FHL Property Adjustments.",
          "properties": {
            "lossBroughtForward": {
              "type": "number",
              "description": "Loss brought forward from earlier years. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "balancingCharge": {
              "type": "number",
              "description": "If an item for which capital allowance was claimed has been sold, given away or is no longer in use. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "privateUseAdjustment": {
              "type": "number",
              "description": "Any expenses incurred that were not solely for the property business. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "businessPremisesRenovationAllowanceBalancingCharges": {
              "type": "number",
              "description": "Income from the sale or grant of a long lease for a premium of renovated business premises within 7 years of first use. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "nonResidentLandlord": {
              "type": "boolean",
              "description": "A boolean to identify that the user is a Non-Resident Landlord. The value must be true or false.",
              "example": "false"
            },
            "rentARoom": {
              "type": "object",
              "description": "Object holding Non UK FHL Rent A Room income shared.",
              "properties": {
                "jointlyLet": {
                  "type": "boolean",
                  "description": "A boolean to identify that the Rent A Room income (RAR) is shared with another individual. The value must be true or false.",
                  "example": "true"
                }
              },
              "required": [
                "jointlyLet"
              ]
            }
          },
          "additionalProperties": false,
          "required": [
            "nonResidentLandlord"
          ]
        },
        "allowances": {
          "type": "object",
          "description": "Object holding UK Non FHL Property Allowances.",
          "properties": {
            "annualInvestmentAllowance": {
              "type": "number",
              "description": "The amount claimed on equipment bought (except cars) up to maximum annual amount. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "zeroEmissionGoodsVehicleAllowance": {
              "type": "number",
              "description": "The amount of zero emission goods vehicle allowance for goods vehicles purchased for business use. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "businessPremisesRenovationAllowance": {
              "type": "number",
              "description": "Allowance for renovation or conversion of derelict business properties. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "otherCapitalAllowance": {
              "type": "number",
              "description": "All other capital allowances. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "costOfReplacingDomesticGoods": {
              "type": "number",
              "description": "Cost of Replacing Domestic Items - formerly Wear and Tear allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "propertyIncomeAllowance": {
              "type": "number",
              "description": "The amount of Tax exemption for individuals with income from land or property. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "electricChargePointAllowance": {
              "type": "number",
              "description": "The expenditure incurred on electric charge-point equipment. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            },
            "structuredBuildingAllowance": {
              "type":  "array",
              "description": "Details about structured building allowance.",
              "items": {
               "type": "object",
                "properties": {
                  "amount": {
                    "type": "number",
                    "description": "The amount of structured building allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                    "example": "5000.99"
                  },
                  "firstYear": {
                    "type": "object",
                    "description": "Object holding UK Non FHL structured building allowance details.",
                    "properties": {
                      "qualifyingDate": {
                        "type": "string",
                        "description": "The date qualified for structured building allowance. Must conform to the format YYYY-MM-DD.",
                        "example": "2020-01-01"
                      },
                      "qualifyingAmountExpenditure": {
                        "type": "number",
                        "description": "The amount of qualifying expenditure. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                        "example": "5000.99"
                      }
                    },
                    "required": [
                      "qualifyingDate",
                      "qualifyingAmountExpenditure"
                    ]
                  },
                  "building": {
                    "type": "object",
                    "description": "Object holding UK Non FHL structured building details. Post code is mandatory and minimum one of name and number field must be supplied.",
                    "properties": {
                      "name": {
                        "type": "string",
                        "description": "The name of the building.",
                        "pattern": "^[0-9a-zA-Z{À-˿’}\\- _&`():.'^]{1,90}$",
                        "example": "Green Oak’s"
                      },
                      "number": {
                        "type": "string",
                        "description": "The number of the building.",
                        "pattern": "^[0-9a-zA-Z{À-˿’}\\- _&`():.'^]{1,90}$",
                        "example": "16"
                      },
                      "postcode": {
                        "type": "string",
                        "description": "The postcode for the building.",
                        "pattern": "^[0-9a-zA-Z{À-˿’}\\- _&`():.'^]{1,90}$",
                        "example": "GF4 9JH"
                      }
                    },
                    "required": [
                      "postcode"
                    ]
                  }
                },
                "required": [
                  "amount",
                  "building"
                ]
              }
            },
            "enhancedStructuredBuildingAllowance": {
              "type": "array",
              "description": "Details about enhanced structured building allowance.",
              "items": {
                "type": "object",
                "properties": {
                  "amount": {
                    "type": "number",
                    "description": "The amount of enhanced structured building allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                    "example": "5000.99"
                  },
                  "firstYear": {
                    "type": "object",
                    "description": "Object holding UK Non FHL enhanced structured building allowance details.",
                    "properties": {
                      "qualifyingDate": {
                        "type": "string",
                        "description": "The date qualified for enhanced structured building allowance. Must conform to the format YYYY-MM-DD.",
                        "example": "2020-01-01"
                      },
                      "qualifyingAmountExpenditure": {
                        "type": "number",
                        "description": "The amount of qualifying expenditure. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                        "example": "5000.99"
                      }
                    },
                    "required": [
                      "qualifyingDate",
                      "qualifyingAmountExpenditure"
                    ]
                  },
                  "building": {
                    "type": "object",
                    "description": "Object holding UK Non FHL enhanced structured building details. Post code is mandatory and minimum one of name and number field must be supplied.",
                    "properties": {
                      "name": {
                        "type": "string",
                        "description": "The name of the building.",
                        "pattern": "^[0-9a-zA-Z{À-˿’}\\- _&`():.'^]{1,90}$",
                        "example": "Green Oak’s"
                      },
                      "number": {
                        "type": "string",
                        "description": "The number of the building.",
                        "pattern": "^[0-9a-zA-Z{À-˿’}\\- _&`():.'^]{1,90}$",
                        "example": "16"
                      },
                      "postcode": {
                        "type": "string",
                        "description": "The postcode for the building.",
                        "pattern": "^[0-9a-zA-Z{À-˿’}\\- _&`():.'^]{1,90}$",
                        "example": "GF4 9JH"
                      }
                    },
                    "required": [
                      "postcode"
                    ]
                  }
                },
                "required": [
                  "amount",
                  "building"
                ]
              }
            },
            "zeroEmissionsCarAllowance": {
              "type": "number",
              "description": "The amount of zero emissions car allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "example": "5000.99"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "A list of endpoint links that indicate possible actions related to the current resource.",
        "properties": {
          "href": {
            "description": "The relative url of the endpoint.",
            "type": "string",
            "example": "/individuals/business/property/uk/TC663795B/XAIS12345678910/annual/2022-23"
          },
          "method": {
            "description": "The HTTP method type for the endpoint.",
            "type": "string",
            "enum": [
              "GET",
              "PUT",
              "DELETE"
            ]
          },
          "rel": {
            "description": "A label for the endpoint, which describes how it is related to the current resource. The rel will be self where the action is retrieval of the same resource.",
            "type": "string",
            "enum": [
              "self",
              "amend-uk-property-annual-submission",
              "delete-property-annual-submission"
            ]
          }
        },
        "required": [
          "href",
          "method",
          "rel"
        ],
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "submittedOn"
  ]
}

=== hmrc/property-business-api/resources/public/api/conf/2.0/examples/uk_property_annual_submission_retrieve/all_other_allowances_response.json
{
  "submittedOn":"2022-06-17T10:53:38Z",
  "ukFhlProperty":{
    "adjustments":{
      "lossBroughtForward":343.34,
      "privateUseAdjustment":454.45,
      "balancingCharge":231.45,
      "periodOfGraceAdjustment":true,
      "businessPremisesRenovationAllowanceBalancingCharges":567.67,
      "nonResidentLandlord":true,
      "rentARoom":{
        "jointlyLet":true
      }
    },
    "allowances":{
      "annualInvestmentAllowance":123.45,
      "businessPremisesRenovationAllowance":345.56,
      "otherCapitalAllowance":345.34,
      "electricChargePointAllowance":453.34,
      "zeroEmissionsCarAllowance":123.12
    }
  },
  "ukNonFhlProperty":{
    "adjustments":{
      "lossBroughtForward":334.45,
      "balancingCharge":565.34,
      "privateUseAdjustment":533.54,
      "businessPremisesRenovationAllowanceBalancingCharges":563.34,
      "nonResidentLandlord":true,
      "rentARoom":{
        "jointlyLet":true
      }
    },
    "allowances":{
      "annualInvestmentAllowance":678.45,
      "zeroEmissionGoodsVehicleAllowance":456.34,
      "businessPremisesRenovationAllowance":573.45,
      "otherCapitalAllowance":452.34,
      "costOfReplacingDomesticGoods":567.34,
      "electricChargePointAllowance":454.34,
      "structuredBuildingAllowance":[
        {
          "amount":234.34,
          "firstYear":{
            "qualifyingDate":"2020-03-29",
            "qualifyingAmountExpenditure":3434.45
          },
          "building":{
            "name":"Plaza",
            "number":"1",
            "postcode":"TF3 4EH"
          }
        }
      ],
      "enhancedStructuredBuildingAllowance":[
        {
          "amount":234.45,
          "firstYear":{
            "qualifyingDate":"2020-05-29",
            "qualifyingAmountExpenditure":453.34
          },
          "building":{
            "name":"Plaza 2",
            "number":"2",
            "postcode":"TF3 4ER"
          }
        }
      ],
      "zeroEmissionsCarAllowance":454.34
    }
  },
  "links": [
    {
      "href": "/individuals/business/property/uk/TC663795B/XAIS12345678910/annual/2022-23",
      "method": "PUT",
      "rel": "amend-uk-property-annual-submission"
    },
    {
      "href": "/individuals/business/property/uk/TC663795B/XAIS12345678910/annual/2022-23",
      "method": "GET",
      "rel": "self"
    },
    {
      "href": "/individuals/business/property/TC663795B/XAIS12345678910/annual/2022-23",
      "method": "DELETE",
      "rel": "delete-property-annual-submission"
    }
  ]
}

=== hmrc/property-business-api/resources/public/api/conf/2.0/examples/uk_property_annual_submission_retrieve/property_allowance_response.json
{
  "submittedOn":"2020-06-17T10:59:47.544Z",
  "ukFhlProperty":{
    "adjustments":{
      "balancingCharge":231.45,
      "periodOfGraceAdjustment":true,
      "businessPremisesRenovationAllowanceBalancingCharges":567.67,
      "nonResidentLandlord":true,
      "rentARoom":{
        "jointlyLet":true
      }
    },
    "allowances":{
      "propertyIncomeAllowance":453.45
    }
  },
  "ukNonFhlProperty":{
    "adjustments":{
      "balancingCharge":565.34,
      "businessPremisesRenovationAllowanceBalancingCharges":563.34,
      "nonResidentLandlord":true,
      "rentARoom":{
        "jointlyLet":true
      }
    },
    "allowances":{
      "propertyIncomeAllowance":342.34
    }
  },
  "links": [
    {
      "href": "/individuals/business/property/uk/TC663795B/XAIS12345678910/annual/2022-23",
      "method": "PUT",
      "rel": "amend-uk-property-annual-submission"
    },
    {
      "href": "/individuals/business/property/uk/TC663795B/XAIS12345678910/annual/2022-23",
      "method": "GET",
      "rel": "self"
    },
    {
      "href": "/individuals/business/property/TC663795B/XAIS12345678910/annual/2022-23",
      "method": "DELETE",
      "rel": "delete-property-annual-submission"
    }
  ]
}
