=== hmrc/property-business-api/resources/public/api/conf/6.0/schemas/foreign_property_cumulative_summary_retrieve/def2/response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "For TY 2026-27 and onwards",
  "type": "object",
  "properties": {
    "submittedOn": {
      "type": "string",
      "description": "The date the foreign property were submitted, in the format YYYY-MM-DDThh:mm:ss.SSSZ",
      "example": "2026-07-07T10:59:47.544Z",
      "format": "date-time"
    },
    "fromDate": {
      "type": "string",
      "description": "The first day that the income and expenses period summary covers. Must conform to the format YYYY-MM-DD.",
      "example": "2026-04-06",
      "format": "date"
    },
    "toDate": {
      "type": "string",
      "description": "The last day that the income and expenses period summary covers. Must conform to the format YYYY-MM-DD.",
      "example": "2026-07-05",
      "format": "date"
    },
    "foreignProperty": {
      "type": "array",
      "description": "Array holding the income and expenses of the user's foreign property business for the period.",
      "items": {
        "type": "object",
        "title": "foreignPropertyEntry",
        "properties": {
          "propertyId": {
            "description": "A unique identifier for each foreign property.",
            "type": "string",
            "format": "uuid",
            "example": "8e8b8450-dc1b-4360-8109-7067337b42cb"
          },
          "income": {
            "type": "object",
            "description": "Object holding the income details for the period.",
            "properties": {
              "rentIncome": {
                "type": "object",
                "description": "Object holding the rent income.",
                "properties": {
                  "rentAmount": {
                    "type": "number",
                    "description": "Total rent and other income from property. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                    "multipleOf": 0.01,
                    "minimum": 0.00,
                    "maximum": 99999999999.99,
                    "example": 5000.99
                  }
                },
                "additionalProperties": false
              },
              "foreignTaxCreditRelief": {
                "type": "boolean",
                "description": "A boolean indicating whether Foreign Tax Credit Relief (FTCR) has been claimed. The value must be true or false.",
                "example": false
              },
              "premiumsOfLeaseGrant": {
                "type": "number",
                "description": "Premiums received for the grant of a lease and other lump sums to possess a property. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                "multipleOf": 0.01,
                "minimum": 0.00,
                "maximum": 99999999999.99,
                "example": 5000.99
              },
              "otherPropertyIncome": {
                "type": "number",
                "description": "Other income from property, such as rent charges and ground rents, income from letting others tip waste on your land, and income for the use of a caravan or houseboat at a fixed location. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                "multipleOf": 0.01,
                "minimum": 0.00,
                "maximum": 99999999999.99,
                "example": 5000.99
              },
              "foreignTaxPaidOrDeducted": {
                "type": "number",
                "description": "The total amount of foreign tax paid or deducted from your income. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                "multipleOf": 0.01,
                "minimum": 0.00,
                "maximum": 99999999999.99,
                "example": 5000.99
              },
              "specialWithholdingTaxOrUkTaxPaid": {
                "type": "number",
                "description": "Tax withheld (in UK Pounds) on certain payments to UK residents or UK Tax paid from rental Income (applies to non-resident landlords only). The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                "multipleOf": 0.01,
                "minimum": 0.00,
                "maximum": 99999999999.99,
                "example": 5000.99
              }
            },
            "additionalProperties": false
          },
          "expenses": {
            "type": "object",
            "description": "Object holding the expenses for the period.",
            "properties": {
              "premisesRunningCosts": {
                "type": "number",
                "description": "Rent, rates, insurance, ground rents and other costs. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
                "multipleOf": 0.01,
                "minimum": -99999999999.99,
                "maximum": 99999999999.99,
                "example": 5000.99
              },
              "repairsAndMaintenance": {
                "type": "number",
                "description": "Property repairs and maintenance. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
                "multipleOf": 0.01,
                "minimum": -99999999999.99,
                "maximum": 99999999999.99,
                "example": 5000.99
              },
              "financialCosts": {
                "type": "number",
                "description": "Loan interest and other financial costs. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
                "multipleOf": 0.01,
                "minimum": -99999999999.99,
                "maximum": 99999999999.99,
                "example": 5000.99
              },
              "professionalFees": {
                "type": "number",
                "description": "Legal, management and other professional fees. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
                "multipleOf": 0.01,
                "minimum": -99999999999.99,
                "maximum": 99999999999.99,
                "example": 5000.99
              },
              "travelCosts": {
                "type": "number",
                "description": "Car, van and travel costs incurred in running a property business. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
                "multipleOf": 0.01,
                "minimum": -99999999999.99,
                "maximum": 99999999999.99,
                "example": 5000.99
              },
              "costOfServices": {
                "type": "number",
                "description": "Cost of services provided, including wages. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
                "multipleOf": 0.01,
                "minimum": -99999999999.99,
                "maximum": 99999999999.99,
                "example": 5000.99
              },
              "residentialFinancialCost": {
                "type": "number",
                "description": "The residential financial cost deductible from rental income (tax relief). The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                "multipleOf": 0.01,
                "minimum": 0.00,
                "maximum": 99999999999.99,
                "example": 5000.99
              },
              "broughtFwdResidentialFinancialCost": {
                "type": "number",
                "description": "Amount of relief brought forward for restricted residential financial costs. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
                "multipleOf": 0.01,
                "minimum": 0.00,
                "maximum": 99999999999.99,
                "example": 5000.99
              },
              "other": {
                "type": "number",
                "description": "Other allowable property expenses. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
                "multipleOf": 0.01,
                "minimum": -99999999999.99,
                "maximum": 99999999999.99,
                "example": 5000.99
              },
              "consolidatedExpenses": {
                "type": "number",
                "description": "The sum of all allowable expenses for the specified period. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
                "multipleOf": 0.01,
                "minimum": -99999999999.99,
                "maximum": 99999999999.99,
                "example": 5000.99
              }
            },
            "additionalProperties": false
          }
        },
        "required": [
          "propertyId"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "submittedOn",
    "fromDate",
    "toDate",
    "foreignProperty"
  ],
  "additionalProperties": false
}

=== hmrc/property-business-api/resources/public/api/conf/6.0/examples/foreign_property_cumulative_summary_retrieve/def2/consolidated_response.json
{
  "submittedOn": "2026-07-07T10:59:47.544Z",
  "fromDate": "2026-04-06",
  "toDate": "2026-07-05",
  "foreignProperty": [
    {
      "propertyId": "8e8b8450-dc1b-4360-8109-7067337b42cb",
      "income": {
        "rentIncome": {
          "rentAmount": 440.31
        },
        "foreignTaxCreditRelief": false,
        "premiumsOfLeaseGrant": 950.48,
        "otherPropertyIncome": 802.49,
        "foreignTaxPaidOrDeducted": 734.18,
        "specialWithholdingTaxOrUkTaxPaid": 85.47
      },
      "expenses": {
        "residentialFinancialCost": 857.78,
        "broughtFwdResidentialFinancialCost": 600.10,
        "consolidatedExpenses": 1500.50
      }
    }
  ]
}
